# Project-wide Gradle settings.
# For more details on how to configure your build by notice, visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects.
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are part of the Android SDK and which are pack of AndroidX.
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX Android stuff.
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Non-transitive R class for faster builds
android.nonTransitiveRClass=true

# Suppress compileSdk warning for compileSdk 35 and 36
android.suppressUnsupportedCompileSdk=35,36

